### ISSUE TITLE
Adding tutorials minor problems

### ISSUE THREAD

**Issue by juddmehr** [BYU-Aeronautics-Club/BYU-Aeronautics-Club.github.io#2]
So it looks like you successfully made a branch, but then didn't use that branch and pushed everything to master.  

Also, you didn't put the foamcutter tutorial in the manufacturing directory, which is where you say it is in your permalink and navigation bar.  So it's not showing up on the website.

You should probably remove your branch, since it wasn't used, and then create a manufacturing directory in the tutorials folder and put the foamcutter stuff in there. (just do it in master, since you're already there), and then see if things work as expected.

**Comment by jspenc42** [comment]
Issues fixed
